name: "YAPS"
version: ${project.version}
author: "Stutiguias"
main: "me.stutiguias.yaps.init.Yaps"
commands:
  cd:
    description: "§bcommands"
permissions:
     yaps.update:
        description: Allow update
        default: op
     yaps.define:
        description: Allow setspawn
        default: op
     yaps.delete:
        description: Allow delspawn
        default: op       
     yaps.reload:
        description: Allow reload
        default: op     
     yaps.wand:
        description: Allow wand
        default: op            
     yaps.sign:
        description: Allow sign
        default: op
     yaps.tp:
        description: Allow tp
        default: op                 
     yaps.info:
        description: Allow info
        default: op               
     yaps.list:
        description: Allow list
        default: op    
     yaps.bypass:
        description: Bypass for admin
        default: op  
     yaps.setexit:
        description: Allow set exit
        default: op          
     yaps.admin:
      description: Gives access to all TimeSpawner commands
      children:
        yaps.update: true
        yaps.define: true
        yaps.delete: true
        yaps.reload: true
        yaps.wand: true
        yaps.sign: true
        yaps.tp: true
        yaps.info: true
        yaps.list: true
        yaps.bypass: true